name: Nginx CI/CD

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        id: docker-build
        uses: docker/build-push-action@v5
        with:
          push: true
          latest: ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/nginx:latest

      - name: Run Dockerfile Linting
        uses: hadolint/hadolint-action@v3
        with:
          dockerfile: ./01-nginx-dockerfile/Dockerfile

      - name: Run Docker Image Vulnerability Scan
        uses: anchore/scan-action@v3
        with:
          image: ${{ steps.docker-build.outputs.digest }}
          fail-on: high 
          severity-cutoff: critical 
          
      - name: Set up Kubernetes context
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy to Kubernetes
        run: kubectl apply -f ./02-k8s-statefulset/nginx-statefulset.yaml 
